### ISSUE TITLE
Reproducibility of the GBMLGG results

### ISSUE THREAD

**Issue by hathawayxxh** [mahmoodlab/PathomicFusion#10]
Hi Richard,

Thank you for sharing the codes and data. I am very interested in your work. I have some concerns regarding the paper and the codes.

1. In your experiments for the pathomic fusion, the histology CNN was frozen and the SNN branch was finetuned. I am curious about why you choose to freeze the CNN branch. Have you ever tried to finetune the two branches together? Or training the two branches simultaneously? 
2. In the arxiv version and the TMI version, the cindex for the histology CNN is different (0.750 vs. 0.792). Are there any difference between the settings or evaluation metrics of these two versions?
3. In your TMI paper, you said the implementation details and some results are provided in the appendix. However, I cannot find the appendix. Could you give a link for the appendix?
4. In your paper, there is a sentence "For cancer grade classification, we did not use mRNAseq expression due to missing data, lack of paired training examples, and because grade is solely determined from histopathologic appearance". If I understand correctly, it means the histological grading task is only related to the histology images rather than the omics data, so why would the pathomic fusion lead to performance gains on this task?

Looking forward to your reply. Thanks a lot for your time and attention. 

Best,
Xiaohan

**Comment by Richarizardd** [comment]
Hi @hathawayxxh,

Thank you for your interest. 
1. Histology CNN was frozen due to mitigate overfitting and training over-parameterized models with low sample-size data. In subsequent work, we have also explored training set-based network approaches for survival prediction of WSIs with multimodal fusion with genomics. [In this work](https://arxiv.org/abs/2108.02278), the aggregation layers are trained together with Genomic SNN, but the CNN for extracting features is still frozen.
2.

**Comment by hathawayxxh** [comment]
Thanks for your reply. My confusion is resolved.
